### PR TITLE
Switch distribution from Module::Build to ExtUtils::MakeMaker

### PR DESCRIPTION
**Pull request by karenetheridge**
This is a redo of PR #3 -- I left that one along as if I were to force-push to the same branch (to update the existing PR), all the comments on the original commits would be lost.

I reduced the number of changes down to a much more minimal set:
- I'd bumped the $VERSION to 0.10 as it's easier to test the resulting distribution when it has the new version, rather than the same version as the previous build (which I've been diffing against locally). But if you've got your own process/timeline for that, fine.
- the `x_contributors` metadata is just information displayed on metacpan to link contributors together; if you don't want that, no problem. (Contributor metadata is discussed at http://blogs.perl.org/users/neilb/2014/08/acknowledge-your-contributors-on-cpan-day.html and the other linked articles.)
- I left in the bugtracker metadata, as you indicated you'd prefer to receive reports directly to email, rather than the default RT queue -- this will be displayed as a link on the distribution's metacpan page in the left sidebar: https://metacpan.org/pod/Text::Glob
- I removed the repository information (which would also be displayed in the left sidebar on metacpan); if maintaining the tooling by hand you'd need to update this by hand if you moved repository locations, but do you do that very often?
- I've removed the generation of README. Some authors find this a helpful file to include in the distribution, but it's certainly not necessary.
- the Makefile.PL backcompat code has been reduced down to the minimal set necessary for the prerequisites being used for this distribution, rather than including all the boilerplate that is useful if you were to have a more complicated distribution.  The transformation of TEST_REQUIRES -> BUILD_REQUIRES -> PREREQ_PM _is_ necessary in order to support perls back to 5.005_03 (as the pod indicates); these perls come with ExtUtils::MakeMaker and CPAN.pm that are too old to understand a CONFIGURE_REQUIRES on a higher EUMM, or even understand the TEST_REQUIRES or BUILD_REQUIRES fields. Although, technically, you don't have any prerequisites that aren't in core, so the code at the end _could_ be dropped as well -- but then this Makefile.PL wouldn't be suitable for cargo-culting into another distribution. How strongly do you feel about keeping the file as short as absolutely possible?

About the CPAN River, and the drive to remove unnecessary uses of Module::Build from its high points:

Neil Bowers described the general concept here -- http://neilb.org/2015/04/20/river-of-cpan.html

As it turns out, Text::Glob sits very high on the river, both because it has no non-core dependencies, and it is used by a _tremendous_ number of distributions, many of which themselves are quite important: http://deps.cpantesters.org/depended-on-by.pl?module=Text::Glob (e.g. Moose depends indirectly on Text::Glob, a few generations removed).

We (the Perl Toolchain Gang) have started looking closely at the top end of the river and considering ways in which we can clean it up. One thing we've been doing which helps out earlier versions of perl, as well as speeding up all installations, is removing unnecessary dependencies on Module::Build, which itself was removed from core last year (see http://www.dagolden.com/index.php/2140/paying-respect-to-modulebuild/). Presently, Text::Glob is the second-highest distribution on the river which uses MB, and its removal there will help move Module::Build's position considerably down-river.

I hope this set of changes is more satisfactory to you. I'm happy to refine further, or answer more questions.

### CODE REVIEW

**Comment by karenetheridge** [comment]
I added a commit to fix the typo that was noted in a few RT tickets, giving credit in git to the initial reporter.

**Comment by karenetheridge** [comment]
..a year has passed... is there anything I can assist with? any further revisions?

**Comment by richardc** [comment]
Drop the typo fix and stage as a distinct PR please

**Comment by karenetheridge** [comment]
The final commit has been moved to #6.

**Comment by karenetheridge** [comment]
Thank you very much!

**Pull request merged**
